include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_put_required_named_parameters_first: true
    lines_longer_than_80_chars: false
    avoid_redundant_argument_values: false
    prefer_if_elements_to_conditional_expressions: false
    require_trailing_commas: true
    always_declare_return_types: true
    sort_pub_dependencies: true
    public_member_api_docs: true

formatter:
  page_width: 120